global:
  scrape_interval: 15s

rule_files:
  - "alert-rules.yml"
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.19:8081']  # for Docker users on Mac/Windows
